### ISSUE TITLE
Consume appContract via query parameter

### ISSUE THREAD

**Issue by vscatarino** [Calindra/cartesi-rollups-hl-graphql#9]
Follow the schema:

` https://optimism.sunodo.app/0x9cb6c6e904ce6bf3ca6d0002b9629acce74ea89b/graphql `
`<protocol>://<host>/<address>/graphql`

**Comment by fabiooshiro** [comment]
I think that's better to also port this to nonodo repo

**Comment by fabiooshiro** [comment]
Ppl decided to 
<protocol>://<host>/graphql/<app-address>
<protocol>://<host>/inspect/<app-address>
